spring.application.name=JavaApp

#prefix : appends prefix to a logical view name to locate the actual physical view resource
spring.mvc.view.prefix=/WEB-INF/views/
#suffix : appends suffix to a logical view name to locate the actual physical view resource
spring.mvc.view.suffix=.jsp
